---
title: "mverse_indexed"
output: html_document
author: "ludmanyboglarka
date: "2026-03-14"
---

# 00. Libraries
```{r}
library(tidyverse)
library(dplyr)
library(readr)
library(magrittr)
```

# 0. Raw data
```{r}
t_zeng_data <- read_csv("data/zeng_replication_data.csv")

t_zhang_data <- read_csv("data/zhang_replication_data.csv")

t_yang_data <- read_csv("data/yang_replication_data.csv")

t_primeprobe_data <- read_tsv("data/prime_probe_global_raw_data.tsv")

t_flanker_data <- read_tsv("data/flanker_raw_data.tsv")
```

# ==============================================================
# 1. Zeng
### preprocessed
```{r}
zeng_raw <- t_zeng_data %>% 
  select(
    trial_index, participant_id, rt, correct, first_trial, congruency, condition
  ) %>% 
  rename(cong = congruency) %>% 
  mutate(
    participant_id = paste0(participant_id, "_zeng"), 
    prev_cong = lag(cong, n = 1), 
    prev_correct = lag(correct, n = 1)
  ) 

zeng_processed <- zeng_raw %>% 
  mutate(
    cong = if_else(cong == "incongruent", -1, 1), 
    prev_cong = if_else(prev_cong == "incongruent", -1, 1)) 
```

### creating block index (pos, neg, neutral)
```{r}
zeng_block <- zeng_processed %>% 
  group_by(participant_id) %>% 
  mutate(
    block_index = cumsum(
      condition != lag(condition, default = first(condition))
    ) + 1
  ) %>% 
  ungroup() %>% 
  select(-first_trial)
```

### write csv
```{r}
write.csv(zeng_block, "/Users/ludmanyboglarka/Documents/metalab/108_cse_empirical/data/indexed_dfs/zeng_indexed.csv")
```


# ===============================================================
# 2. Zhang 
### block index
```{r}
zhang_block <- t_zhang_data %>% 
  arrange(participant_id) %>% 
  group_by(participant_id) %>% 
  mutate(
    block_index = {
      ## flags where new block starts
      blockstart <- case_when(
        task %in% c("pause", "pause_practice") ~ 1,
         T ~ 0
      )
      cumsum(blockstart) + 1
    } 
  ) %>% 
  ungroup()
```

### processed
```{r}
zhang_raw <- zhang_block %>% 
  select(
    trial_index, participant_id, rt, response, task, block, congruency, correct, block, id, block_index
  )

zhang_processed <- zhang_raw %>% 
  mutate(
    cong = case_when(
      congruency == "no_conflict" ~ 1,
      congruency %in% c("low_conflict", "high_conflict") ~ -1)) %>% 
  filter(task == "response") %>%  
  mutate(
    prev_cong = lag(cong, n = 1), 
    prev_correct = lag(correct, n = 1),
    participant_id = paste0(participant_id, "_zhang"), 
    is_practice = case_when(
      (block == "practice") ~ 1,
      (is.na(block)) ~ 0)
    ) %>% 
  select(-response, -task, -id) %>% 
  rename(name = block)
```

### write csv
```{r}
write.csv(zhang_processed, "/Users/ludmanyboglarka/Documents/metalab/108_cse_empirical/data/indexed_dfs/zhang_indexed.csv")
```


# ===============================================================
# 3. Yang 
### block index
```{r}
yang_raw <- t_yang_data %>% 
  mutate(feedback = case_when(grepl(">✘</div>",stimulus) ~ "visual_punishment", # flagging different feedback events in new variable
                                grepl("&#11036", stimulus) ~ "neutral",
                                grepl(">✘<br>5 garast veszítettél</div>",stimulus) ~ "monetary_loss",
                                grepl("✔",stimulus) ~ "tickmark"
                                ),
         prev_feedback = ifelse(task=="probe", lag(feedback,n=4),""), # Flagging previous feedback in probe trial
         prev_loss = ifelse(prev_feedback == "monetary_loss", 1,0), # Flagging if monetary loss happened before this probe 
         prev_correct = lag(correct,n = 5), # flagging previous correct
         prev_congruency = lag(congruency, n = 5), # creating previous congruency variable
         block_feedback_type = lead(feedback_type)) # moving feedback type data to probe variable

yang_block <- yang_raw %>% 
  filter(
    task == "probe"
  ) %>% 
  group_by(subj_code) %>% 
  mutate(
    blockstart = case_when(
      (is.na(prev_congruency)) & (is.na(prev_correct)) ~ 1,
      T ~ 0
      ), 
    block_index = cumsum(blockstart)
    ) %>% 
  ungroup()
```

### processed
```{r}
yang_processed <- yang_block %>% 
  select(
    rt, trial_index, subj_code, congruency, name, correct, prev_correct, prev_congruency, block_index
  ) %>% 
  mutate(
    is_practice = ifelse(name == "practice", 1, 0), 
    subj_code = paste0(subj_code, "_yang"), 
    prev_congruency = if_else(prev_congruency == "incongruent", -1, 1),
    congruency = if_else(congruency == "incongruent", -1, 1)
  ) %>% 
  rename(cong = congruency,
         prev_cong = prev_congruency, 
         participant_id = subj_code)
```

### write csv
```{r}
write.csv(yang_processed, "/Users/ludmanyboglarka/Documents/metalab/108_cse_empirical/data/indexed_dfs/yang_indexed.csv")
```


# ===============================================================
# 4. Prime-probe
### block index, trial index, type_code (?)
```{r}
primeprobe_raw <- t_primeprobe_data %>% 
  select(
    -prime, -probe, -filename, 
    -loc, -task, -consent_time.x, -event_log, -gender, -age, -education, -consent_time.y, -duplicate_drop
  ) %>% 
  mutate(rt = (response_time-probe_onset))

primeprobe_processed <- primeprobe_raw %>% 
  select(
    -prime_onset, -prime_offset, -probe_onset, -probe_offset, -response_time
  ) %>% 
  rename(cong = is_congruent) %>% 
  mutate( 
    cong = ifelse(cong == 1, 1, -1),
    correct = ifelse(response_target == response_content, T, F), 
    prev_correct = lag(correct, n = 1), 
    prev_cong = lag(cong, n = 1), 
    participant_id = paste0(participant_id, "_primeprobe")
  ) %>% 
  mutate(
    is_first_trial = 
      case_when(block > lag(block) ~ T, T ~ F)
  ) %>% 
  select(-version, -response_target, -response_content, -type_code) %>% 
  rename(trial_index = trial_id, 
         block_index = block)
```

### write csv
```{r}
write.csv(primeprobe_processed, "/Users/ludmanyboglarka/Documents/metalab/108_cse_empirical/data/indexed_dfs/primeprobe_indexed.csv")
```


# ===============================================================
# 5. Flanker
### block index, trial index, type_code (?)
```{r}
flanker_raw <- t_flanker_data %>% 
  select(
    trial_id, type_code, block, is_practice, 
    response_target, is_congruent, stim_onset, stim_offset, response_time, 
    response_content, participant_id
  ) %>% 
  mutate(rt = (response_time - stim_onset))

flanker_processed <- flanker_raw %>% 
  select(
    -stim_onset, -stim_offset, -response_time
  ) %>% 
  rename(cong = is_congruent) %>% 
  mutate( 
    cong = ifelse(cong == 1, 1, -1),
    correct = ifelse(response_target == response_content, T, F), 
    prev_correct = lag(correct, n = 1), 
    prev_cong = lag(cong, n = 1), 
    participant_id = paste0(participant_id, "_flanker")
  ) %>% 
  mutate(
    is_first_trial = 
      case_when(block > lag(block) ~ T, T ~ F)
  ) %>% 
  select(-response_target, -response_content, -type_code) %>% 
  rename(trial_index = trial_id, 
         block_index = block)
```

### write csv
```{r}
write.csv(flanker_processed, "/Users/ludmanyboglarka/Documents/metalab/108_cse_empirical/data/indexed_dfs/flanker_indexed.csv")
```

# ===============================================================
# 6. bind_rows
```{r}
flanker_processed$rt <- as.numeric(flanker_processed$rt)
primeprobe_processed$rt <- as.numeric(primeprobe_processed$rt)
yang_processed$rt <- as.numeric(yang_processed$rt)
zhang_processed$rt <- as.numeric(zhang_processed$rt)
zeng_block$rt <- as.numeric(zeng_block$rt)

all_indexed <- bind_rows(flanker_processed, primeprobe_processed, yang_processed, zhang_processed, zeng_block)

write.csv(all_indexed, "/Users/ludmanyboglarka/Documents/metalab/108_cse_empirical/data/indexed_dfs/all_indexed.csv")
```

